Made modal
js-tasks-ru/htmlcss-20241107_saganjules pull request #11
Opened 2024-12-01 19:55 UTC by JulieSagan

2024-12-01 19:56 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-12-02 10:21 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-12-03 12:49 UTC, GSemikozov requested changes

2024-12-03 12:49 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__overlay {
в целом - лишний элемент, фон можно задать в .modal

2024-12-03 12:49 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    max-height: 294px;
лишнее ограничение высоты

2024-12-03 16:55 UTC, GSemikozov requested changes

2024-12-03 16:55 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +            <div class="modal__overlay">
лишний элемент, можно удалить

2024-12-04 22:59 UTC, GSemikozov approved these changes

2024-12-04 22:59 UTC, merged