Used background-image
js-tasks-ru/htmlcss-20241107_saganjules pull request #15
Opened 2024-12-16 10:49 UTC by JulieSagan

2024-12-16 10:49 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-12-16 12:02 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-12-16 18:50 UTC, GSemikozov requested changes

2024-12-16 18:50 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +@media screen and (max-width: 768px) {
если mobile-first, то везде min-width

2024-12-17 07:06 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-12-17 07:06 UTC, JulieSagan commented on 06-lection4/02-background-image/background-image.css
> +@media screen and (max-width: 768px) {
путаюсь всё время с этой особенностью

2024-12-19 14:00 UTC, GSemikozov approved these changes

2024-12-19 14:00 UTC, merged