Created checkbox
js-tasks-ru/htmlcss-20241107_saganjules pull request #19
Opened 2024-12-23 21:29 UTC by JulieSagan

2024-12-23 21:29 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-12-25 10:30 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-12-30 21:23 UTC, GSemikozov requested changes

2024-12-30 21:23 UTC, GSemikozov commented on 07-lection5/01-checkbox/index.html
> +            <div class="checkbox__wrapper">
вот это еще надо удалить

2025-01-07 09:03 UTC, GSemikozov approved these changes

2025-01-07 09:03 UTC, merged