Created radio buttons
js-tasks-ru/htmlcss-20241107_saganjules pull request #20
Opened 2024-12-25 21:30 UTC by JulieSagan

2024-12-25 21:30 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-12-30 14:14 UTC, GSemikozov requested changes

2024-12-30 14:14 UTC, GSemikozov commented on 07-lection5/02-radio/index.html
> +            <legend class="radio__legend_hidden"></legend>
а почему hidden? и почему модификатор без элемента который он модифицирует?

2024-12-30 14:14 UTC, GSemikozov commented on 07-lection5/02-radio/index.html
> +        <fieldset class="radio">
радио кнопки в fieldset складывать не нужно

2024-12-30 14:14 UTC, GSemikozov commented on 07-lection5/02-radio/index.html
> +            <label class="radio__label">
блок начинается именно здесь

2024-12-30 14:14 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +.radio {
см комменты выше

2024-12-30 21:24 UTC, GSemikozov requested changes

2024-12-30 21:24 UTC, GSemikozov commented on 07-lection5/02-radio/index.html
> +            <div class="radio__wrapper">
лишний незакрывающийся div)

2024-12-30 21:24 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +.radio__wrapper {
это лишний элемент, верно?

2024-12-30 21:31 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-12-30 21:37 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2025-01-07 09:03 UTC, GSemikozov approved these changes

2025-01-07 09:04 UTC, jsru-1 commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2025-01-07 09:04 UTC, GSemikozov approved these changes

2025-01-07 09:04 UTC, merged