Just created
js-tasks-ru/htmlcss-20241107_saganjules pull request #22
Opened 2024-12-30 21:39 UTC by JulieSagan

2024-12-30 21:39 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-12-31 23:51 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2025-01-01 20:56 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2025-01-07 09:57 UTC, GSemikozov requested changes

2025-01-07 09:57 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    padding-left: 24px;
не хватает паддингов

2025-01-07 09:57 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input-wrapper {
.input__wrapper?
wrapper это обычно обертка снаружи, если внутри - то наверно .input__inner или как-то так

2025-01-07 09:57 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    display: flex;
флексом делать не обязательно

2025-01-07 09:57 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    right: 16px;
и + top

2025-01-07 09:57 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__field_success::placeholder {
.input_success .input__field {}
там цвет у value меняется, не у плейсхолдера

2025-01-07 09:57 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__field_invalid {
.input_invalid .input__field

2025-01-07 09:57 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__field_invalid ~ .input__icon {
.input_invalid .input__icon_invalid

(в разметке присутствуют сразу 2 иконки)

2025-01-07 09:57 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__field_disabled {
такого состояния в макете вроде нет

2025-01-07 11:34 UTC, JulieSagan commented on 07-lection5/04-input/input.css
> +.input__field_disabled {
<img width="1121" alt="Screenshot 2025-01-07 at 13 32 17" src="https://github.com/user-attachments/assets/9bde95be-9506-4aef-8134-0994565b534e" />

Это необязательное задание, но оно там есть :))

2025-01-07 17:37 UTC, JulieSagan commented on 07-lection5/04-input/input.css
> +    padding-left: 24px;
добавила

2025-01-07 17:42 UTC, JulieSagan commented on 07-lection5/04-input/input.css
> +.input-wrapper {
исправила на input-control

2025-01-07 17:53 UTC, JulieSagan commented on 07-lection5/04-input/input.css
> +    display: flex;
<img width="428" alt="Screenshot 2025-01-07 at 19 53 05" src="https://github.com/user-attachments/assets/dd645ced-69a6-40f6-a9be-adbe3f563107" />

если я не делаю флексом получается так

2025-01-07 18:11 UTC, JulieSagan commented on 07-lection5/04-input/input.css
> +    display: flex;
А разве плохо использовать флекс для выравнивания в данном контексте?

2025-01-07 18:25 UTC, JulieSagan commented on 07-lection5/04-input/input.css
> +    right: 16px;
и +transform: translate(-50%)

2025-01-07 18:33 UTC, JulieSagan commented on 07-lection5/04-input/input.css
> +.input__field_success::placeholder {
убрала

2025-01-07 18:52 UTC, JulieSagan commented on 07-lection5/04-input/input.css
> +.input__field_invalid ~ .input__icon {
не понимаю, что ты имеешь в виду?

2025-01-07 19:07 UTC, JulieSagan commented on 07-lection5/04-input/input.css
> +.input__field_invalid ~ .input__icon {
я поняла так, что нужно добавить модификаторы к иконкам:
.input__icon_success {
    color: var(--blue, #374FC7);
}

.input__icon_invalid {
    color: var(--error, #F03D3E);
}

2025-01-08 07:39 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    display: flex;
просто а что мы выравниваем? там же один инпут, который влияет на высоту этого враппера, а иконка - абсолютом

2025-01-08 07:40 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    right: 16px;
translateY(-50%)

2025-01-08 07:40 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__field_invalid ~ .input__icon {
и к блоку - .input_invalid + .input_success, и в зависимости от того что у блока - показываем нужную иконку

2025-01-08 07:41 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__field_disabled {
да, но там даже указано, что надо использовать :disabled, а не модификатор _disabled (это же динамическое состояние для инпута, просто мы пока не добавляем никаких правил валидации)

2025-01-08 07:42 UTC, GSemikozov requested changes

2025-01-08 07:42 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input-control {
если элемент блока, то .input__control

2025-01-08 13:47 UTC, JulieSagan commented on 07-lection5/04-input/input.css
> +.input__field_disabled {
да, вот я сделала через псевдокласс 
<img width="389" alt="Screenshot 2025-01-08 at 15 46 34" src="https://github.com/user-attachments/assets/5b29929e-a760-4439-8516-f8d74791de86" />

2025-01-09 10:02 UTC, GSemikozov approved these changes

2025-01-09 10:02 UTC, merged