03-lection1/01-button
js-tasks-ru/htmlcss-20241107_saganjules pull request #4
Opened 2024-11-16 13:12 UTC by JulieSagan

2024-11-16 13:13 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-11-16 13:27 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-11-16 21:55 UTC, GSemikozov requested changes

2024-11-16 21:55 UTC, GSemikozov commented on components/01-button/button.css
> +.button_primary:disabled {
достаточно одного общего состояния .button:disabled

2024-11-16 21:55 UTC, GSemikozov commented on components/01-button/button.css
> +    background-color: var(--primary);
и тогда фон менять не надо

2024-11-17 10:28 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-11-17 10:58 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-11-17 11:14 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-11-17 12:46 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-11-18 16:59 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-11-18 17:06 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-11-19 09:04 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-11-19 12:23 UTC, GSemikozov approved these changes

2024-11-19 12:23 UTC, merged