Made histogram
js-tasks-ru/htmlcss-20241107_saganjules pull request #6
Opened 2024-11-20 17:07 UTC by JulieSagan

2024-11-20 17:07 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-11-20 17:10 UTC, GSemikozov requested changes

2024-11-20 17:10 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding: 24px;
`16 24 24`

2024-11-20 17:10 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding-bottom: 40px;
margin-bottom: 39px

2024-11-20 17:10 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    line-height: 1.5;
в текстовых элементах надо указывать и font-size, и font-family

2024-11-20 17:10 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    text-decoration: none;
margin-top: 3px

2024-11-20 17:10 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.bar {
.histogram__bar

2024-11-20 17:10 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    max-height: 100%;
лишнее

2024-11-20 17:10 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    flex-basis: 10%;
лишнее

2024-11-20 17:18 UTC, JulieSagan commented on 04-lection2/01-histogram/histogram.css
> +    padding: 24px;
done

2024-11-20 17:18 UTC, JulieSagan commented on 04-lection2/01-histogram/histogram.css
> +    padding-bottom: 40px;
done

2024-11-20 17:21 UTC, JulieSagan commented on 04-lection2/01-histogram/histogram.css
> +    text-decoration: none;
done. Но по идее они на одной линии должны быть. Скорее всего это ошибка макета

2024-11-20 17:22 UTC, JulieSagan commented on 04-lection2/01-histogram/histogram.css
> +.bar {
done

2024-11-20 17:23 UTC, JulieSagan commented on 04-lection2/01-histogram/histogram.css
> +    max-height: 100%;
done

2024-11-20 17:24 UTC, JulieSagan commented on 04-lection2/01-histogram/histogram.css
> +    flex-basis: 10%;
done

2024-11-20 17:27 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-11-20 17:36 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-11-20 18:16 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-11-20 18:27 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-11-21 04:56 UTC, GSemikozov approved these changes

2024-11-21 04:57 UTC, merged