Calendar
js-tasks-ru/htmlcss-20241107_saganjules pull request #9
Opened 2024-11-28 15:55 UTC by JulieSagan

2024-11-28 15:56 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-11-28 16:17 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-11-28 16:23 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-11-28 21:36 UTC, GSemikozov requested changes

2024-11-28 21:36 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    padding: 30px 30px 40px 30px;
`28 26 32`

2024-11-28 21:36 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    max-width: 500px;
304

2024-11-28 21:36 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__days {
не стоит отделять .calendar__days и .calendar__dates - на самом деле это один общий грид

2024-11-28 21:36 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    margin-bottom: 24px;
и тогда вот этот отступ будет лишним

2024-11-28 21:36 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__day,
вместо двух элементов можем использовать один, например .calendar__item, а отличия - через модификаторы

2024-11-28 21:36 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    padding: 5px;
кажется лишним (если квадраты - флексы с выравниваем контента по центру)

2024-11-30 14:02 UTC, JulieSagan commented on 05-lection3/03-calendar/calendar.css
> +    padding: 30px 30px 40px 30px;
Это, плохой паттерн в дизайне (могу судить, я сама дизайнер), как-будто пьяный школьник делал отступы. Но как скажешь, сделаю такие

2024-11-30 14:16 UTC, JulieSagan commented on 05-lection3/03-calendar/calendar.css
> +    padding: 30px 30px 40px 30px;
Извини, но тут я буду с тобой спорить (имею право, я сама 😊):
1. Боковые отступы дизайнер, который рисовал компоненты, отсчитывал от единственного неизменного элемента — это дни недели. И если посмотришь, то они по 30px с каждой стороны (см. скриншоты). Неправильно брать расчёт расстояний до края от изменяемых да ещё и центрированных чисел месяца. Либо это должен был быть объединённый блок с постоянными шириной и высотой, но в макете это отдельные цифры (что тоже не комельфо);
2. Я заметила, что в макете присутствуют расстояния или размеры, где больше похоже на общую ошибку, чем на задумку. Обычно смещения на пару пикселей могут происходить в процессе работы случайно. Ну, или это ваша хитрая задумка на проверку внимания 😊
3. По макету следующие отступы: 28 30 40 30, если быть точным.

<img width="936" alt="Screenshot 2024-11-30 at 4 04 22 PM" src="https://github.com/user-attachments/assets/7e6d85ea-777b-4516-9612-69ed0cd8d20d">
<img width="944" alt="Screenshot 2024-11-30 at 4 04 40 PM" src="https://github.com/user-attachments/assets/017a2401-827c-4717-8914-420137818959">
<img width="1023" alt="Screenshot 2024-11-30 at 4 06 15 PM" src="https://github.com/user-attachments/assets/da7790ac-a40c-4c2a-97fe-fa626a73bcbf">

2024-11-30 15:19 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    padding: 30px 30px 40px 30px;
здесь все очень просто считается:
1) у нас есть грид - квадрат, который, в свою очередь, разделен на 7 рядом по 7 более мелких квадратов
2) так что отсчет отступа слева и справа, а также снизу нужно вести с учетом размера одной такой ячейки
3) в макете это например синий квадрат слева (смотрим его размеры, смотрим отступ слева - такой же будет справа, потом учитывая высоту - считаем отступ снизу)
4) будет неправильно считать отступы от текста внутри ячейки, а не от самой ячейки

2024-11-30 15:19 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    padding: 30px 30px 40px 30px;
так что если быть точным - `28 26 32`

2024-11-30 18:14 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-11-30 19:18 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-12-03 12:45 UTC, GSemikozov requested changes

2024-12-03 12:45 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    padding: 28px 26px 40px 32px;
все-таки `28 26 32` :)

2024-12-03 12:45 UTC, GSemikozov commented on 05-lection3/03-calendar/index.html
> +            <div class="calendar__body">
а где стили для этого элемента? неясно что он делает)

2024-12-03 12:45 UTC, GSemikozov commented on 05-lection3/03-calendar/index.html
> +                <div class="calendar__item">
item заворачивает другие item-ы? видимо это ошибка

2024-12-04 22:58 UTC, GSemikozov approved these changes

2024-12-04 22:58 UTC, merged